name: C++ CI & Google Test

permissions:
  packages: write

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
    
env: 
  USERNAME: Pugga12
  VCPKG_ROOT: ${{github.workspace}}/vcpkg
  VCPKG_EXE: ${{ github.workspace }}/vcpkg/vcpkg
  FEED_URL: https://nuget.pkg.github.com/<OWNER>/index.json
  VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/Pugga12/index.json,readwrite"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: true
          
      - name: Checkout vcpkg
        uses: actions/checkout@v7
        with:
          repository: microsoft/vcpkg
          path: vcpkg
      
      - name: Bootstrap vcpkg
        shell: bash
        run: ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh
      
      - name: Install mono
        run: sudo apt install mono-complete
      
      - name: Add NuGet sources
        shell: bash
        run: |
          mono `${{ env.VCPKG_EXE }} fetch nuget | tail -n 1` \
            sources add \
            -Source "${{ env.FEED_URL }}" \
            -StorePasswordInClearText \
            -Name GitHubPackages \
            -UserName "${{ env.USERNAME }}" \
            -Password "${{ secrets.GITHUB_TOKEN }}"
          mono `${{ env.VCPKG_EXE }} fetch nuget | tail -n 1` \
            setapikey "${{ secrets.GITHUB_TOKEN }}" \
            -Source "${{ env.FEED_URL }}"
      
      - name: Cache FetchContent
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/build/_deps
          key: ${{ runner.os }}-fetchcontent-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-fetchcontent-

      - name: Configure CMake
        run: >
          cmake -B build 
          -DCMAKE_BUILD_TYPE=Debug 
          -DDZSUNGEL_BUILD_TESTS=ON
          -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake

      - name: Build Project & Tests
        run: cmake --build build --config Debug -j $(nproc)

      - name: Run Tests (CTest)
        run: |
          cd build
          ctest --output-on-failure -C Debug